apiVersion: v2
name: sda-db
version: 2.0.4
appVersion: v2.0.12
kubeVersion: '>= 1.26.0'
description: Database component for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sensitive-data-archive
