apiVersion: v2
name: sda-mq
version: "0.6.0"
appVersion: "v0.0.163"
description: RabbitMQ component for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sda-helm
