apiVersion: v2
name: sda-mq
version: 2.0.22
appVersion: v3.0.31
kubeVersion: '>= 1.26.0'
description: RabbitMQ component for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sda-helm
