app:
  middleware: "token-clientversion"
  minimalcliversion: "v0.2.0"

log:
  level: "debug"
  format: "json"

storage:
  archive:
    s3:
      endpoint: "http://s3:9000"
      access_key: "access"
      secret_key: "secretkey"
      bucket_prefix: "archive"
      region: "us-east-1"
      disable_https: true
    posix:
      path: "/tmp"

grpc:
  host: reencrypt
  port: 50051

c4gh:
  filepath: "./dev_utils/c4gh.sec.pem"
  passphrase: "oaagCP1YgAZeEyl2eJAkHv9lkcWXWFgm"
  privateKeys:
  - filepath: "./dev_utils/c4gh.sec.pem"
    passphrase: "oaagCP1YgAZeEyl2eJAkHv9lkcWXWFgm"

db:
  host: "localhost"
  port: 5432
  user: "download"
  password: "download"
  database: "sda"
  sslmode: "disable"

oidc:
  cacert: "./dev_utils/certs/ca.pem"
  # oidc configuration API must have values for "userinfo_endpoint" and "jwks_uri"
  configuration:
    url: "http://mockauth:8000/.well-known/openid-configuration"
