{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if ne "" .Values.global.inbox.storageType }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-inbox
  labels:
    app: {{ template "sda.fullname" . }}-inbox
spec:
  ports:
  - name: inbox
    port: {{ template "inboxServicePort" . }}
    targetPort: inbox
    protocol: TCP
  - name: inbox-liveness
    port: 8001
    targetPort: liveness-port
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-inbox
{{- end }}
{{- end }}
