{{- if and (ne "" .Values.global.sync.api.password) (ne "" .Values.global.sync.api.user) }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-syncapi
  labels:
    app: {{ template "sda.fullname" . }}-syncapi
spec:
  ports:
  - name: syncapi
    port: {{ ternary 443 80 ( .Values.global.tls.enabled ) }}
    targetPort: syncapi
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-syncapi
{{- end }}
{{- end }}
